services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/openfga --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mongo_data: